version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin@juliana
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres-network
    volumes:
      - postgres:/data/postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@juliana.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "2345:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
    postgres: